[project]
name = "fastfilter"
version = "0.0.1"
dynamic = ["dependencies"]
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
[project.scripts]
fastfilter = "fastfilter:fastfilter"
